### PR TITLE
Refactoring MapControl for Blazor

### PR DESCRIPTION
**Pull request by daniellor**
Hi,

Minor changes in MapControl definition in Blazor.

Daniel

### CODE REVIEW

**Comment by inforithmics** [comment]
I like the reorganization. Makes the Mapsui Blazor Control less Special. 

Do I have the permission to retarget the commits and make a pull request to the Parent repository 
https://github.com/Mapsui/Mapsui?

**Comment by daniellor** [comment]
You can retarget the commits and make a pull request to https://github.com/Mapsui/Mapsui. 

I am glad you extend Mapsui to Blazor. In the near future I will try to support the development of Mapsui for the Blazor platform.

**Comment by inforithmics** [comment]
Here is the rebased pull request with compilation fixes (due to merge conflict).
@daniellor  Can you sign the CLA?
https://github.com/Mapsui/Mapsui/pull/1796

**Comment by thomasstockermc** [comment]
Closing this as the checkins where merged into mapsui main repository

**Comment by inforithmics** [comment]
This was merged here so closing this pull request

https://github.com/Mapsui/Mapsui/pull/1796

Thanks for the changes

**Pull request closed without merging**
